spring.application.name=empleados-api

# Conexión a MongoDB (contenedor empleados-mongo)
spring.mongodb.uri=mongodb://academia:academia123@localhost:27017/empleados_db?authSource=admin

# Crea al arrancar los índices de @Indexed (necesario para el email único)
spring.data.mongodb.auto-index-creation=true

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Paginación
spring.data.web.pageable.max-page-size=50